#!/bin/bash
# merge_audit.sh — Gom 3 Báo Cáo Audit Thành 1 File Cuối
# Chạy bởi: Tùng Diag (sau khi 3 sub-agents hoàn thành)
# Output: AUDIT_REPORT_FINAL.md → đưa cho MIXTURE_OF_EXPERTS_ROUTER.md đọc

set -e

AUDIT_DIR="${1:-.}"  # Thư mục chứa các file audit, default: thư mục hiện tại
OUTPUT="$AUDIT_DIR/AUDIT_REPORT_FINAL.md"
TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S")

echo "🔍 STMAI Audit Merge — Running at $TIMESTAMP"
echo ""

# === Kiểm tra 3 file input bắt buộc ===
MISSING=0
for f in "audit_business.md" "audit_technical.md" "audit_integration.md"; do
    if [ ! -f "$AUDIT_DIR/$f" ]; then
        echo "❌ MISSING: $AUDIT_DIR/$f"
        MISSING=1
    else
        echo "✅ FOUND: $AUDIT_DIR/$f"
    fi
done

if [ "$MISSING" -eq 1 ]; then
    echo ""
    echo "⛔ ABORT: Không đủ 3 báo cáo. Tùng Diag phải đợi tất cả sub-agents hoàn thành."
    exit 1
fi

echo ""
echo "📝 Merging into $OUTPUT ..."

# === Viết Header ===
cat > "$OUTPUT" << EOF
# AUDIT_REPORT_FINAL.md
# Báo Cáo Kiểm Định Toàn Diện (12 Chiều TDD)
# Generated: $TIMESTAMP
# Generated by: merge_audit.sh | Orchestrated by: Tùng Diag

---

## ⚠️ LƯU Ý CHO MIXTURE_OF_EXPERTS_ROUTER.md
Đây là báo cáo đầu vào DUY NHẤT mà Router cần đọc.
Đừng đọc 3 file riêng lẻ.

---

EOF

# === Merge từng phần ===
echo "## PHẦN 1: NGHIỆP VỤ & TỔ CHỨC (Chiều 1-3, 9-10)" >> "$OUTPUT"
echo "_Nguồn: audit_business.md (Conan Req-Aud)_" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$AUDIT_DIR/audit_business.md" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## PHẦN 2: KỸ THUẬT & HẠ TẦNG (Chiều 4-8)" >> "$OUTPUT"
echo "_Nguồn: audit_technical.md (Phúc SA + Mộc Arch-Chal)_" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$AUDIT_DIR/audit_technical.md" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## PHẦN 3: TÍCH HỢP BE↔FE (Chiều 11-12)" >> "$OUTPUT"
echo "_Nguồn: audit_integration.md (Xuân Spec-Rev + Huyền QA)_" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$AUDIT_DIR/audit_integration.md" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# === Footer ===
cat >> "$OUTPUT" << EOF
## KẾT LUẬN (Điền bởi Tùng Diag sau khi đọc 3 phần trên)

**Tổng Điểm Cảnh Báo:**
- CRITICAL: ___
- HIGH: ___
- MEDIUM: ___
- LOW: ___

**FLOW OF WORKFLOWS (Chuyển cho ROUTER):**
> [Tùng Diag điền vào đây trước khi đưa cho Router]

EOF

echo ""
echo "✅ DONE: $OUTPUT created successfully!"
echo "👉 Next: Tùng Diag đọc file này, điền KẾT LUẬN, rồi đưa cho MIXTURE_OF_EXPERTS_ROUTER.md"
